export const LANGUAGE_KEY = "duovoice.language";
export const DEFAULT_LANGUAGE = "en";
export const SUPPORTED_LANGUAGES = ["en", "fr", "es", "de"];

const dictionaries = {
  en: {
    "brand.subtitle": "Local intercom", "status.offline": "Offline", "status.connected": "Connected",
    "common.settings": "Settings", "common.quit": "Quit", "common.cancel": "Cancel", "common.close": "Close", "common.open": "Open", "common.apply": "Apply changes", "common.reset": "Restore defaults",
    "update.checking": "Checking for updates…", "update.current": "No update available · Click to check", "update.available": "Update available · v{version} · Click to download", "update.error": "Unable to check · Click to retry", "update.preparing": "Preparing v{version}…", "update.downloading": "Downloading v{version}…", "update.installing": "Installing v{version}…",
    "connection.title": "Connection", "connection.subtitle": "Choose the PC you want to communicate with.", "connection.machineName": "This machine name", "connection.machinePlaceholder": "Name visible on the network", "connection.remote": "Remote computer", "connection.searching": "Searching for a PC…", "connection.none": "No PC detected — add an IP", "connection.favorites": "Favorites", "connection.quickActions": "Quick actions", "connection.ipPlaceholder": "IP address, e.g. 192.168.1.25", "connection.ipHint": "You can also add an IP address directly.", "connection.connect": "Connect", "connection.disconnect": "Disconnect", "connection.available": "Available", "connection.unavailable": "Unavailable", "connection.favoriteAdded": "{name} added to favorites.", "connection.favoriteRemoved": "Favorite removed.",
    "audio.title": "Audio", "audio.subtitle": "Microphone and PC output.", "audio.microphone": "Microphone", "audio.output": "Audio output", "audio.noise": "Noise reduction", "audio.disabled": "Disabled", "audio.enabled": "Enabled", "audio.noiseSettings": "Settings", "audio.localRnnoise": "RNNoise · local processing", "audio.intensity": "Intensity", "audio.moreSuppression": "Higher = stronger suppression", "audio.natural": "Natural", "audio.balanced": "Balanced", "audio.aggressive": "Aggressive", "audio.noiseHint": "Noise reduction is applied to the microphone before network transmission.", "audio.remoteVolume": "Remote volume", "audio.boost": "Allow volume above 100%", "audio.mute": "Mute", "audio.unmute": "Unmute",
    "state.title": "Status", "state.searching": "Searching for computers on the local network…", "state.latency": "Audio latency", "state.mode": "Mode", "state.lan": "Direct LAN", "state.active": "Bidirectional audio active.", "state.disconnected": "Disconnected.",
    "settings.title": "Settings", "settings.subtitle": "DuoVoice preferences", "settings.version": "Version", "settings.versionDesc": "Currently installed version and updates.", "settings.installedVersion": "Installed version", "settings.versionHint": "Click the version to choose another release.", "settings.history": "History", "settings.lastUpdateUnavailable": "Last update: unavailable", "settings.startup": "Startup", "settings.startupDesc": "Control startup behavior.", "settings.autostart": "Start DuoVoice with Windows/Linux", "settings.trayIcon": "Show the system tray icon", "settings.startHidden": "Start minimized to tray", "settings.savedAutomatically": "Settings are saved automatically.", "settings.close": "Close behavior", "settings.closeDesc": "Choose what the X button does.", "settings.closeAction": "Close button action", "settings.minimizeTray": "Minimize to tray", "settings.quitDuoVoice": "Quit DuoVoice", "settings.closeHint": "In tray mode, DuoVoice also disappears from the taskbar.",
    "settings.language": "Language", "settings.languageDesc": "Choose the application language.",
    "settings.appearance": "Appearance", "settings.appearanceDesc": "Choose a soft accent color for the interface.", "settings.themesPlus": "Themes++", "settings.themesPlusDesc": "Applies a complete palette to DuoVoice and the system tray.", "settings.scale": "Interface scale", "settings.scaleDesc": "Adjust DuoVoice size for your display and comfort.", "settings.mainApp": "Main application", "settings.trayControl": "System tray controls", "settings.audio": "Audio", "settings.audioDesc": "Devices, volume and noise reduction are kept between launches.", "settings.savedVolume": "Saved volume", "settings.noiseReduction": "Noise reduction",
    "version.choose": "Choose a version", "version.chooseDesc": "Reinstall a previous signed DuoVoice release.", "version.searching": "Searching available versions…", "version.installQuestion": "Install {version}?", "version.install": "Install", "version.none": "No previous signed release available.",
    "quit.title": "Quit DuoVoice?", "quit.body": "The application and audio will be completely stopped.",
    "tray.host": "Host", "tray.noHost": "No host connected", "tray.choosePc": "Choose a PC…", "tray.noDetected": "No host detected", "tray.connection": "Connection", "tray.quickControls": "Quick controls", "tray.github": "GitHub page", "tray.openDuoVoice": "Open DuoVoice",
    "language.changed": "Language changed.", "autostart.enabled": "Automatic startup enabled.", "autostart.disabled": "Automatic startup disabled.", "trayIcon.enabled": "System tray icon enabled.", "trayIcon.disabled": "System tray icon disabled. Start minimized is disabled to keep DuoVoice accessible."
  },
  fr: {
    "brand.subtitle": "Intercom local", "status.offline": "Hors ligne", "status.connected": "Connecté",
    "common.settings": "Paramètres", "common.quit": "Quitter", "common.cancel": "Annuler", "common.close": "Fermer", "common.open": "Ouvrir", "common.apply": "Appliquer les modifications", "common.reset": "Rétablir par défaut",
    "update.checking": "Vérification des mises à jour…", "update.current": "Pas de mise à jour disponible · Cliquez pour vérifier", "update.available": "Mise à jour disponible · v{version} · Cliquez pour télécharger", "update.error": "Vérification impossible · Cliquez pour réessayer", "update.preparing": "Préparation de v{version}…", "update.downloading": "Téléchargement de v{version}…", "update.installing": "Installation de v{version}…",
    "connection.title": "Connexion", "connection.subtitle": "Choisissez le PC avec lequel communiquer.", "connection.machineName": "Nom de cette machine", "connection.machinePlaceholder": "Nom visible sur le réseau", "connection.remote": "Ordinateur distant", "connection.searching": "Recherche d'un PC…", "connection.none": "Aucun PC détecté — ajoutez une IP", "connection.favorites": "Favoris", "connection.quickActions": "Actions rapides", "connection.ipPlaceholder": "Adresse IP, ex. 192.168.1.25", "connection.ipHint": "Vous pouvez aussi ajouter directement une adresse IP.", "connection.connect": "Se connecter", "connection.disconnect": "Se déconnecter", "connection.available": "Disponible", "connection.unavailable": "Indisponible", "connection.favoriteAdded": "{name} ajouté aux favoris.", "connection.favoriteRemoved": "Favori retiré.",
    "audio.title": "Audio", "audio.subtitle": "Microphone et sortie du PC.", "audio.microphone": "Microphone", "audio.output": "Sortie audio", "audio.noise": "Réduction de bruit", "audio.disabled": "Désactivée", "audio.enabled": "Activée", "audio.noiseSettings": "Réglages", "audio.localRnnoise": "RNNoise · traitement local", "audio.intensity": "Intensité", "audio.moreSuppression": "Plus fort = suppression plus marquée", "audio.natural": "Naturel", "audio.balanced": "Équilibré", "audio.aggressive": "Agressif", "audio.noiseHint": "La réduction est appliquée au micro avant l'envoi réseau.", "audio.remoteVolume": "Volume distant", "audio.boost": "Autoriser le volume au-dessus de 100%", "audio.mute": "Muet", "audio.unmute": "Réactiver",
    "state.title": "État", "state.searching": "Recherche des ordinateurs sur le réseau local…", "state.latency": "Latence audio", "state.mode": "Mode", "state.lan": "LAN direct", "state.active": "Audio bidirectionnel actif.", "state.disconnected": "Déconnecté.",
    "settings.title": "Paramètres", "settings.subtitle": "Préférences de DuoVoice", "settings.version": "Version", "settings.versionDesc": "Version actuellement installée et mises à jour.", "settings.installedVersion": "Version installée", "settings.versionHint": "Cliquer sur la version pour choisir une autre release.", "settings.history": "Historique", "settings.lastUpdateUnavailable": "Dernière mise à jour : non disponible", "settings.startup": "Démarrage", "settings.startupDesc": "Contrôlez le comportement au lancement.", "settings.autostart": "Démarrer DuoVoice avec Windows/Linux", "settings.trayIcon": "Afficher l’icône dans le systray", "settings.startHidden": "Démarrer minimisé dans le tray", "settings.savedAutomatically": "Les réglages sont enregistrés automatiquement.", "settings.close": "Fermeture", "settings.closeDesc": "Choisissez ce que fait le bouton X.", "settings.closeAction": "Action du bouton fermer", "settings.minimizeTray": "Réduire dans le tray", "settings.quitDuoVoice": "Quitter DuoVoice", "settings.closeHint": "En mode tray, DuoVoice disparaît aussi de la barre des tâches.",
    "settings.language": "Langue", "settings.languageDesc": "Choisissez la langue de l’application.",
    "settings.appearance": "Apparence", "settings.appearanceDesc": "Choisissez une couleur douce pour l’interface.", "settings.themesPlus": "Thèmes++", "settings.themesPlusDesc": "Applique une palette complète à DuoVoice et au systray.", "settings.scale": "Échelle de l’interface", "settings.scaleDesc": "Ajustez la taille générale de DuoVoice selon votre écran et votre confort.", "settings.mainApp": "Application principale", "settings.trayControl": "Contrôle rapide du systray", "settings.audio": "Audio", "settings.audioDesc": "Les périphériques, le volume et la réduction de bruit sont conservés entre les lancements.", "settings.savedVolume": "Volume enregistré", "settings.noiseReduction": "Réduction de bruit",
    "version.choose": "Choisir une version", "version.chooseDesc": "Réinstallez une version précédente signée de DuoVoice.", "version.searching": "Recherche des versions disponibles…", "version.installQuestion": "Installer {version} ?", "version.install": "Installer", "version.none": "Aucune version précédente signée disponible.",
    "quit.title": "Quitter DuoVoice ?", "quit.body": "L’application et l’audio seront complètement arrêtés.",
    "tray.host": "Hôte", "tray.noHost": "Aucun hôte connecté", "tray.choosePc": "Choisir un PC…", "tray.noDetected": "Aucun hôte détecté", "tray.connection": "Connexion", "tray.quickControls": "Contrôles rapides", "tray.github": "Page GitHub", "tray.openDuoVoice": "Ouvrir DuoVoice",
    "language.changed": "Langue modifiée.", "autostart.enabled": "Démarrage automatique activé.", "autostart.disabled": "Démarrage automatique désactivé.", "trayIcon.enabled": "Icône du systray activée.", "trayIcon.disabled": "Icône du systray désactivée. Le démarrage minimisé est désactivé pour garder DuoVoice accessible."
  },
  es: {
    "brand.subtitle": "Intercom local", "status.offline": "Sin conexión", "status.connected": "Conectado",
    "common.settings": "Ajustes", "common.quit": "Salir", "common.cancel": "Cancelar", "common.close": "Cerrar", "common.open": "Abrir", "common.apply": "Aplicar cambios", "common.reset": "Restablecer valores",
    "update.checking": "Buscando actualizaciones…", "update.current": "No hay actualizaciones · Haz clic para comprobar", "update.available": "Actualización disponible · v{version} · Haz clic para descargar", "update.error": "No se pudo comprobar · Haz clic para reintentar",
    "connection.title": "Conexión", "connection.subtitle": "Elige el PC con el que quieres comunicarte.", "connection.machineName": "Nombre de este equipo", "connection.machinePlaceholder": "Nombre visible en la red", "connection.remote": "Equipo remoto", "connection.searching": "Buscando un PC…", "connection.none": "No se detectó ningún PC — añade una IP", "connection.favorites": "Favoritos", "connection.quickActions": "Acciones rápidas", "connection.ipPlaceholder": "Dirección IP, ej. 192.168.1.25", "connection.ipHint": "También puedes añadir una dirección IP directamente.", "connection.connect": "Conectar", "connection.disconnect": "Desconectar", "connection.available": "Disponible", "connection.unavailable": "No disponible",
    "audio.title": "Audio", "audio.subtitle": "Micrófono y salida del PC.", "audio.microphone": "Micrófono", "audio.output": "Salida de audio", "audio.noise": "Reducción de ruido", "audio.disabled": "Desactivada", "audio.enabled": "Activada", "audio.noiseSettings": "Ajustes", "audio.intensity": "Intensidad", "audio.remoteVolume": "Volumen remoto", "audio.boost": "Permitir volumen superior al 100%", "audio.mute": "Silenciar", "audio.unmute": "Reactivar",
    "state.title": "Estado", "state.searching": "Buscando equipos en la red local…", "state.latency": "Latencia de audio", "state.mode": "Modo", "state.lan": "LAN directa",
    "settings.title": "Ajustes", "settings.subtitle": "Preferencias de DuoVoice", "settings.version": "Versión", "settings.versionDesc": "Versión instalada y actualizaciones.", "settings.installedVersion": "Versión instalada", "settings.versionHint": "Haz clic en la versión para elegir otra release.", "settings.history": "Historial", "settings.lastUpdateUnavailable": "Última actualización: no disponible", "settings.startup": "Inicio", "settings.startupDesc": "Controla el comportamiento al iniciar.", "settings.autostart": "Iniciar DuoVoice con Windows/Linux", "settings.trayIcon": "Mostrar el icono en la bandeja", "settings.startHidden": "Iniciar minimizado en la bandeja", "settings.savedAutomatically": "Los ajustes se guardan automáticamente.", "settings.close": "Cierre", "settings.closeDesc": "Elige qué hace el botón X.", "settings.closeAction": "Acción del botón cerrar", "settings.minimizeTray": "Minimizar a la bandeja", "settings.quitDuoVoice": "Salir de DuoVoice", "settings.closeHint": "En modo bandeja, DuoVoice también desaparece de la barra de tareas.", "settings.language": "Idioma", "settings.languageDesc": "Elige el idioma de la aplicación.", "settings.appearance": "Apariencia", "settings.appearanceDesc": "Elige un color de acento suave.", "settings.themesPlus": "Temas++", "settings.themesPlusDesc": "Aplica una paleta completa a DuoVoice y a la bandeja.", "settings.scale": "Escala de la interfaz", "settings.scaleDesc": "Ajusta el tamaño de DuoVoice a tu pantalla.", "settings.mainApp": "Aplicación principal", "settings.trayControl": "Controles de la bandeja", "settings.audio": "Audio", "settings.audioDesc": "Los dispositivos, volumen y reducción de ruido se conservan entre inicios.", "settings.savedVolume": "Volumen guardado", "settings.noiseReduction": "Reducción de ruido",
    "version.choose": "Elegir una versión", "version.chooseDesc": "Reinstala una versión anterior firmada de DuoVoice.", "version.searching": "Buscando versiones disponibles…", "version.installQuestion": "¿Instalar {version}?", "version.install": "Instalar", "version.none": "No hay una versión anterior firmada disponible.", "quit.title": "¿Salir de DuoVoice?", "quit.body": "La aplicación y el audio se detendrán por completo.", "tray.host": "Host", "tray.noHost": "Ningún host conectado", "tray.choosePc": "Elegir un PC…", "tray.noDetected": "Ningún host detectado", "tray.connection": "Conexión", "tray.quickControls": "Controles rápidos", "tray.github": "Página de GitHub", "tray.openDuoVoice": "Abrir DuoVoice", "language.changed": "Idioma cambiado."
  },
  de: {
    "brand.subtitle": "Lokale Gegensprechanlage", "status.offline": "Offline", "status.connected": "Verbunden",
    "common.settings": "Einstellungen", "common.quit": "Beenden", "common.cancel": "Abbrechen", "common.close": "Schließen", "common.open": "Öffnen", "common.apply": "Änderungen anwenden", "common.reset": "Standard wiederherstellen",
    "update.checking": "Suche nach Updates…", "update.current": "Kein Update verfügbar · Zum Prüfen klicken", "update.available": "Update verfügbar · v{version} · Zum Herunterladen klicken", "update.error": "Prüfung nicht möglich · Zum Wiederholen klicken",
    "connection.title": "Verbindung", "connection.subtitle": "Wähle den PC für die Kommunikation.", "connection.machineName": "Name dieses Geräts", "connection.machinePlaceholder": "Im Netzwerk sichtbarer Name", "connection.remote": "Entfernter Computer", "connection.searching": "Suche nach einem PC…", "connection.none": "Kein PC erkannt — IP hinzufügen", "connection.favorites": "Favoriten", "connection.quickActions": "Schnellaktionen", "connection.ipPlaceholder": "IP-Adresse, z. B. 192.168.1.25", "connection.ipHint": "Du kannst auch direkt eine IP-Adresse hinzufügen.", "connection.connect": "Verbinden", "connection.disconnect": "Trennen", "connection.available": "Verfügbar", "connection.unavailable": "Nicht verfügbar",
    "audio.title": "Audio", "audio.subtitle": "Mikrofon und PC-Ausgabe.", "audio.microphone": "Mikrofon", "audio.output": "Audioausgabe", "audio.noise": "Rauschunterdrückung", "audio.disabled": "Deaktiviert", "audio.enabled": "Aktiviert", "audio.noiseSettings": "Einstellungen", "audio.intensity": "Intensität", "audio.remoteVolume": "Remote-Lautstärke", "audio.boost": "Lautstärke über 100% erlauben", "audio.mute": "Stumm", "audio.unmute": "Ton an",
    "state.title": "Status", "state.searching": "Suche nach Computern im lokalen Netzwerk…", "state.latency": "Audio-Latenz", "state.mode": "Modus", "state.lan": "Direktes LAN",
    "settings.title": "Einstellungen", "settings.subtitle": "DuoVoice-Einstellungen", "settings.version": "Version", "settings.versionDesc": "Installierte Version und Updates.", "settings.installedVersion": "Installierte Version", "settings.versionHint": "Auf die Version klicken, um eine andere Release zu wählen.", "settings.history": "Verlauf", "settings.lastUpdateUnavailable": "Letztes Update: nicht verfügbar", "settings.startup": "Start", "settings.startupDesc": "Startverhalten steuern.", "settings.autostart": "DuoVoice mit Windows/Linux starten", "settings.trayIcon": "Symbol im Infobereich anzeigen", "settings.startHidden": "Minimiert im Infobereich starten", "settings.savedAutomatically": "Einstellungen werden automatisch gespeichert.", "settings.close": "Schließen", "settings.closeDesc": "Wähle die Aktion der X-Schaltfläche.", "settings.closeAction": "Aktion der Schließen-Schaltfläche", "settings.minimizeTray": "In den Infobereich minimieren", "settings.quitDuoVoice": "DuoVoice beenden", "settings.closeHint": "Im Infobereich-Modus verschwindet DuoVoice auch aus der Taskleiste.", "settings.language": "Sprache", "settings.languageDesc": "Wähle die Sprache der Anwendung.", "settings.appearance": "Darstellung", "settings.appearanceDesc": "Wähle eine dezente Akzentfarbe.", "settings.themesPlus": "Themes++", "settings.themesPlusDesc": "Wendet eine vollständige Palette auf DuoVoice und den Infobereich an.", "settings.scale": "Oberflächenskalierung", "settings.scaleDesc": "Passe die Größe von DuoVoice an deinen Bildschirm an.", "settings.mainApp": "Hauptanwendung", "settings.trayControl": "Infobereich-Steuerung", "settings.audio": "Audio", "settings.audioDesc": "Geräte, Lautstärke und Rauschunterdrückung bleiben gespeichert.", "settings.savedVolume": "Gespeicherte Lautstärke", "settings.noiseReduction": "Rauschunterdrückung",
    "version.choose": "Version auswählen", "version.chooseDesc": "Eine frühere signierte DuoVoice-Version neu installieren.", "version.searching": "Verfügbare Versionen werden gesucht…", "version.installQuestion": "{version} installieren?", "version.install": "Installieren", "version.none": "Keine frühere signierte Version verfügbar.", "quit.title": "DuoVoice beenden?", "quit.body": "Anwendung und Audio werden vollständig beendet.", "tray.host": "Host", "tray.noHost": "Kein Host verbunden", "tray.choosePc": "PC auswählen…", "tray.noDetected": "Kein Host erkannt", "tray.connection": "Verbindung", "tray.quickControls": "Schnellsteuerung", "tray.github": "GitHub-Seite", "tray.openDuoVoice": "DuoVoice öffnen", "language.changed": "Sprache geändert."
  }
};

export function normalizeLanguage(value) {
  return SUPPORTED_LANGUAGES.includes(value) ? value : DEFAULT_LANGUAGE;
}

export function getLanguage() {
  return normalizeLanguage(localStorage.getItem(LANGUAGE_KEY) || DEFAULT_LANGUAGE);
}

export function setLanguage(language) {
  const normalized = normalizeLanguage(language);
  localStorage.setItem(LANGUAGE_KEY, normalized);
  return normalized;
}

export function t(key, vars = {}, language = getLanguage()) {
  const lang = normalizeLanguage(language);
  const template = dictionaries[lang]?.[key] ?? dictionaries.en[key] ?? key;
  return String(template).replace(/\{(\w+)\}/g, (_, name) => vars[name] ?? `{${name}}`);
}

export function localeForLanguage(language = getLanguage()) {
  return ({ en: "en-US", fr: "fr-FR", es: "es-ES", de: "de-DE" })[normalizeLanguage(language)] || "en-US";
}

export function applyStaticTranslations(root = document, language = getLanguage()) {
  const lang = normalizeLanguage(language);
  document.documentElement.lang = lang;
  root.querySelectorAll("[data-i18n]").forEach((element) => {
    element.textContent = t(element.dataset.i18n, {}, lang);
  });
  root.querySelectorAll("[data-i18n-placeholder]").forEach((element) => {
    element.setAttribute("placeholder", t(element.dataset.i18nPlaceholder, {}, lang));
  });
  root.querySelectorAll("[data-i18n-title]").forEach((element) => {
    element.setAttribute("title", t(element.dataset.i18nTitle, {}, lang));
  });
  root.querySelectorAll("[data-i18n-aria]").forEach((element) => {
    element.setAttribute("aria-label", t(element.dataset.i18nAria, {}, lang));
  });
}
