export const LANGUAGE_KEY = "duovoice.language";
export const DEFAULT_LANGUAGE = "en";
export const SUPPORTED_LANGUAGES = ["en", "fr", "es", "de"];

const dictionaries = {
  en: {
    "brand.subtitle": "Local intercom", "status.offline": "Offline", "status.connected": "Connected",
    "common.settings": "Settings", "common.quit": "Quit", "common.cancel": "Cancel", "common.close": "Close", "common.open": "Open", "common.apply": "Apply changes", "common.reset": "Restore defaults",
    "update.checking": "Checking for updates…", "update.current": "No update available · Click to check", "update.available": "Update available · v{version} · Click to download", "update.error": "Unable to check · Click to retry", "update.preparing": "Preparing v{version}…", "update.downloading": "Downloading v{version}…", "update.installing": "Installing v{version}…",
    "group.title": "Session", "group.subtitle": "One-to-one or LAN group", "group.empty": "No session configured.", "group.members": "Active participants", "group.add": "Add to session", "group.remove": "Remove from session", "group.limit": "A group session can contain up to 12 participants including this computer.", "group.reconnecting": "Reconnecting…", "group.duo": "Duo", "group.groupMode": "LAN group", "group.trayTitle": "Session", "group.trayDuo": "Duo · {count} PCs", "group.trayGroup": "Group · {count} PCs", "group.none": "No session", "group.duoSummary": "Duo · {count} participants", "group.groupSummary": "Group · {count} participants", "group.participantsTitle": "Session participants", "group.participantCount": "{count} participants", "group.popupHint": "Use the + button next to the selected computer to add it to this session.",
    "group.duoHint": "Direct connection", "group.groupHint": "Named rooms on the LAN", "group.rooms": "Group rooms", "group.roomsShort": "rooms", "group.visibleHint": "Rooms are automatically visible to DuoVoice PCs on your LAN.", "group.roomPlaceholder": "Room name, e.g. Gaming", "group.createRoom": "Create", "group.availableRooms": "Available rooms", "group.noRooms": "No room visible yet. Create one or wait for another DuoVoice PC.", "group.join": "Join", "group.leave": "Leave", "group.host": "Host", "group.hostUnavailable": "Host unavailable", "group.full": "Full", "group.roomLabel": "Room", "group.created": "Room {name} created and visible on the LAN.", "group.createFailed": "Unable to create room", "group.joined": "Joined room {name}.", "group.joinFailed": "Unable to join room", "group.left": "Room left.", "group.you": "You", "group.waiting": "Room active", "group.closed": "The room was closed by its host.",
    "recent.title": "Recent connections", "recent.desc": "The most recently used LAN peers.", "recent.empty": "No recent connection yet.",
    "diagnostics.title": "Diagnostics", "diagnostics.desc": "Useful information for audio and local-network troubleshooting.", "diagnostics.computer": "Computer", "diagnostics.ip": "Local IPv4", "diagnostics.ports": "LAN ports", "diagnostics.engine": "Audio engine", "diagnostics.peers": "Session peers", "diagnostics.devices": "Active devices", "diagnostics.log": "Log file",
    "connection.title": "Connection", "connection.subtitle": "Choose the PC you want to communicate with.", "connection.machineName": "This machine name", "connection.machinePlaceholder": "Name visible on the network", "connection.remote": "Remote computer", "connection.searching": "Searching for a PC…", "connection.none": "No PC detected — add an IP", "connection.favorites": "Favorites", "connection.quickActions": "Quick actions", "connection.ipPlaceholder": "IP address, e.g. 192.168.1.25", "connection.ipHint": "You can also add an IP address directly.", "connection.connect": "Connect", "connection.disconnect": "Disconnect", "connection.available": "Available", "connection.unavailable": "Unavailable", "connection.favoriteAdded": "{name} added to favorites.", "connection.favoriteRemoved": "Favorite removed.", "connection.favoritesCount": "{count} favorites",
    "audio.title": "Audio", "audio.subtitle": "Microphone and PC output.", "audio.microphone": "Microphone", "audio.output": "Audio output", "audio.noise": "Noise reduction", "audio.disabled": "Disabled", "audio.enabled": "Enabled", "audio.noiseSettings": "Settings", "audio.localRnnoise": "RNNoise · local processing", "audio.intensity": "Intensity", "audio.moreSuppression": "Higher = stronger suppression", "audio.natural": "Natural", "audio.balanced": "Balanced", "audio.aggressive": "Aggressive", "audio.noiseHint": "Noise reduction is applied to the microphone before network transmission.", "audio.remoteVolume": "Remote volume", "audio.boost": "Allow volume above 100%", "audio.mute": "Mute", "audio.unmute": "Unmute", "audio.actions": "Audio actions", "audio.actionsDesc": "Quick tools for the current audio setup.", "audio.test": "Test audio", "audio.testing": "Testing…", "audio.testDone": "Audio test played on the selected output.", "audio.testFailed": "Audio test failed", "audio.monitor": "Test microphone", "audio.monitoring": "Stop mic test", "audio.monitorHint": "Microphone monitoring is active in the selected output. Speak to check the level and routing.", "audio.monitorStopped": "Microphone monitoring stopped.", "audio.monitorFailed": "Microphone test failed",
    "state.title": "Status", "state.searching": "Searching for computers on the local network…", "state.latency": "Audio latency", "state.mode": "Mode", "state.lan": "Direct LAN", "state.active": "Bidirectional audio active.", "state.disconnected": "Disconnected.", "state.network": "Network", "state.session": "Session", "state.discovery": "Discovery", "state.ports": "Ports",
    "settings.title": "Settings", "settings.subtitle": "DuoVoice preferences", "settings.version": "Version", "settings.versionDesc": "Currently installed version and updates.", "settings.installedVersion": "Installed version", "settings.versionHint": "Click the version to choose another release.", "settings.history": "History", "settings.lastUpdateUnavailable": "Last update: unavailable", "settings.startup": "Startup", "settings.startupDesc": "Control startup behavior.", "settings.autostart": "Start DuoVoice with Windows", "settings.trayIcon": "Show the system tray icon", "settings.startHidden": "Start minimized to tray", "settings.savedAutomatically": "Settings are saved automatically.", "settings.close": "Close behavior", "settings.closeDesc": "Choose what the X button does.", "settings.closeAction": "Close button action", "settings.minimizeTray": "Minimize to tray", "settings.quitDuoVoice": "Quit DuoVoice", "settings.closeHint": "In tray mode, DuoVoice also disappears from the taskbar.",
    "settings.language": "Language", "settings.languageDesc": "Choose the application language.",
    "settings.appearance": "Appearance", "settings.appearanceDesc": "Choose a soft accent color for the interface.", "settings.themesPlus": "Themes++", "settings.themesPlusDesc": "Applies a complete palette to DuoVoice and the system tray.", "settings.scale": "Interface scale", "settings.scaleDesc": "Adjust DuoVoice size for your display and comfort.", "settings.mainApp": "Main application", "settings.trayControl": "System tray controls", "settings.audio": "Audio", "settings.audioDesc": "Devices, volume and noise reduction are kept between launches.", "settings.savedVolume": "Saved volume", "settings.noiseReduction": "Noise reduction",
    "version.choose": "Choose a version", "version.chooseDesc": "Reinstall a previous signed DuoVoice release.", "version.searching": "Searching available versions…", "version.installQuestion": "Install {version}?", "version.install": "Install", "version.none": "No previous signed release available.",
    "quit.title": "Quit DuoVoice?", "quit.body": "The application and audio will be completely stopped.",
    "tray.host": "Host", "tray.noHost": "No host connected", "tray.choosePc": "Choose a PC…", "tray.noDetected": "No host detected", "tray.connection": "Connection", "tray.quickControls": "Quick controls", "tray.github": "GitHub page", "tray.openDuoVoice": "Open DuoVoice", "tray.session": "Session", "tray.favorites": "Favorites", "tray.quitSession": "Leave session", "tray.addParticipant": "Add participant", "tray.noFavorites": "No favorites saved",
    "language.changed": "Language changed.", "autostart.enabled": "Automatic startup enabled.", "autostart.disabled": "Automatic startup disabled.", "trayIcon.enabled": "System tray icon enabled.", "trayIcon.disabled": "System tray icon disabled. Start minimized is disabled to keep DuoVoice accessible."
  },
  fr: {
    "brand.subtitle": "Intercom local", "status.offline": "Hors ligne", "status.connected": "Connecté",
    "common.settings": "Paramètres", "common.quit": "Quitter", "common.cancel": "Annuler", "common.close": "Fermer", "common.open": "Ouvrir", "common.apply": "Appliquer les modifications", "common.reset": "Rétablir par défaut",
    "update.checking": "Vérification des mises à jour…", "update.current": "Pas de mise à jour disponible · Cliquez pour vérifier", "update.available": "Mise à jour disponible · v{version} · Cliquez pour télécharger", "update.error": "Vérification impossible · Cliquez pour réessayer", "update.preparing": "Préparation de v{version}…", "update.downloading": "Téléchargement de v{version}…", "update.installing": "Installation de v{version}…",
    "group.title": "Session", "group.subtitle": "Duo ou groupe LAN", "group.empty": "Aucune session configurée.", "group.members": "Participants actifs", "group.add": "Ajouter à la session", "group.remove": "Retirer de la session", "group.limit": "Une session de groupe peut contenir jusqu’à 12 participants, cet ordinateur compris.", "group.reconnecting": "Reconnexion…", "group.duo": "Duo", "group.groupMode": "Groupe LAN", "group.trayTitle": "Session", "group.trayDuo": "Duo · {count} PC", "group.trayGroup": "Groupe · {count} PC", "group.none": "Aucune session", "group.duoSummary": "Duo · {count} participants", "group.groupSummary": "Groupe · {count} participants", "group.participantsTitle": "Participants de la session", "group.participantCount": "{count} participants", "group.popupHint": "Utilisez le bouton + à côté du PC sélectionné pour l’ajouter à cette session.",
    "group.duoHint": "Connexion directe", "group.groupHint": "Salons nommés sur le réseau", "group.rooms": "Salons de groupe", "group.roomsShort": "salons", "group.visibleHint": "Les salons sont automatiquement visibles par les PC DuoVoice de votre réseau local.", "group.roomPlaceholder": "Nom du salon, ex. Gaming", "group.createRoom": "Créer", "group.availableRooms": "Salons disponibles", "group.noRooms": "Aucun salon visible pour le moment. Créez-en un ou attendez un autre PC DuoVoice.", "group.join": "Rejoindre", "group.leave": "Quitter", "group.host": "Hôte", "group.hostUnavailable": "Hôte indisponible", "group.full": "Complet", "group.roomLabel": "Salon", "group.created": "Salon {name} créé et visible sur le réseau.", "group.createFailed": "Impossible de créer le salon", "group.joined": "Salon {name} rejoint.", "group.joinFailed": "Impossible de rejoindre le salon", "group.left": "Salon quitté.", "group.you": "Vous", "group.waiting": "Salon actif", "group.closed": "Le salon a été fermé par son hôte.",
    "recent.title": "Connexions récentes", "recent.desc": "Les derniers pairs LAN utilisés.", "recent.empty": "Aucune connexion récente.",
    "diagnostics.title": "Diagnostics", "diagnostics.desc": "Informations utiles pour diagnostiquer l’audio et le réseau local.", "diagnostics.computer": "Ordinateur", "diagnostics.ip": "IPv4 locale", "diagnostics.ports": "Ports LAN", "diagnostics.engine": "Moteur audio", "diagnostics.peers": "Pairs de session", "diagnostics.devices": "Périphériques actifs", "diagnostics.log": "Fichier journal",
    "connection.title": "Connexion", "connection.subtitle": "Choisissez le PC avec lequel communiquer.", "connection.machineName": "Nom de cette machine", "connection.machinePlaceholder": "Nom visible sur le réseau", "connection.remote": "Ordinateur distant", "connection.searching": "Recherche d'un PC…", "connection.none": "Aucun PC détecté — ajoutez une IP", "connection.favorites": "Favoris", "connection.quickActions": "Actions rapides", "connection.ipPlaceholder": "Adresse IP, ex. 192.168.1.25", "connection.ipHint": "Vous pouvez aussi ajouter directement une adresse IP.", "connection.connect": "Se connecter", "connection.disconnect": "Se déconnecter", "connection.available": "Disponible", "connection.unavailable": "Indisponible", "connection.favoriteAdded": "{name} ajouté aux favoris.", "connection.favoriteRemoved": "Favori retiré.", "connection.favoritesCount": "{count} favoris",
    "audio.title": "Audio", "audio.subtitle": "Microphone et sortie du PC.", "audio.microphone": "Microphone", "audio.output": "Sortie audio", "audio.noise": "Réduction de bruit", "audio.disabled": "Désactivée", "audio.enabled": "Activée", "audio.noiseSettings": "Réglages", "audio.localRnnoise": "RNNoise · traitement local", "audio.intensity": "Intensité", "audio.moreSuppression": "Plus fort = suppression plus marquée", "audio.natural": "Naturel", "audio.balanced": "Équilibré", "audio.aggressive": "Agressif", "audio.noiseHint": "La réduction est appliquée au micro avant l'envoi réseau.", "audio.remoteVolume": "Volume distant", "audio.boost": "Autoriser le volume au-dessus de 100%", "audio.mute": "Muet", "audio.unmute": "Réactiver", "audio.actions": "Actions audio", "audio.actionsDesc": "Outils rapides pour la configuration audio actuelle.", "audio.test": "Tester audio", "audio.testing": "Test…", "audio.testDone": "Test audio joué sur la sortie sélectionnée.", "audio.testFailed": "Échec du test audio", "audio.monitor": "Test microphone", "audio.monitoring": "Arrêter le test micro", "audio.monitorHint": "Le retour du microphone est actif dans la sortie sélectionnée. Parlez pour vérifier le niveau et le routage.", "audio.monitorStopped": "Retour microphone arrêté.", "audio.monitorFailed": "Échec du test microphone",
    "state.title": "État", "state.searching": "Recherche des ordinateurs sur le réseau local…", "state.latency": "Latence audio", "state.mode": "Mode", "state.lan": "LAN direct", "state.active": "Audio bidirectionnel actif.", "state.disconnected": "Déconnecté.", "state.network": "Réseau", "state.session": "Session", "state.discovery": "Détection LAN", "state.ports": "Ports",
    "settings.title": "Paramètres", "settings.subtitle": "Préférences de DuoVoice", "settings.version": "Version", "settings.versionDesc": "Version actuellement installée et mises à jour.", "settings.installedVersion": "Version installée", "settings.versionHint": "Cliquer sur la version pour choisir une autre release.", "settings.history": "Historique", "settings.lastUpdateUnavailable": "Dernière mise à jour : non disponible", "settings.startup": "Démarrage", "settings.startupDesc": "Contrôlez le comportement au lancement.", "settings.autostart": "Démarrer DuoVoice avec Windows", "settings.trayIcon": "Afficher l’icône dans le systray", "settings.startHidden": "Démarrer minimisé dans le tray", "settings.savedAutomatically": "Les réglages sont enregistrés automatiquement.", "settings.close": "Fermeture", "settings.closeDesc": "Choisissez ce que fait le bouton X.", "settings.closeAction": "Action du bouton fermer", "settings.minimizeTray": "Réduire dans le tray", "settings.quitDuoVoice": "Quitter DuoVoice", "settings.closeHint": "En mode tray, DuoVoice disparaît aussi de la barre des tâches.",
    "settings.language": "Langue", "settings.languageDesc": "Choisissez la langue de l’application.",
    "settings.appearance": "Apparence", "settings.appearanceDesc": "Choisissez une couleur douce pour l’interface.", "settings.themesPlus": "Thèmes++", "settings.themesPlusDesc": "Applique une palette complète à DuoVoice et au systray.", "settings.scale": "Échelle de l’interface", "settings.scaleDesc": "Ajustez la taille générale de DuoVoice selon votre écran et votre confort.", "settings.mainApp": "Application principale", "settings.trayControl": "Contrôle rapide du systray", "settings.audio": "Audio", "settings.audioDesc": "Les périphériques, le volume et la réduction de bruit sont conservés entre les lancements.", "settings.savedVolume": "Volume enregistré", "settings.noiseReduction": "Réduction de bruit",
    "version.choose": "Choisir une version", "version.chooseDesc": "Réinstallez une version précédente signée de DuoVoice.", "version.searching": "Recherche des versions disponibles…", "version.installQuestion": "Installer {version} ?", "version.install": "Installer", "version.none": "Aucune version précédente signée disponible.",
    "quit.title": "Quitter DuoVoice ?", "quit.body": "L’application et l’audio seront complètement arrêtés.",
    "tray.host": "Hôte", "tray.noHost": "Aucun hôte connecté", "tray.choosePc": "Choisir un PC…", "tray.noDetected": "Aucun hôte détecté", "tray.connection": "Connexion", "tray.quickControls": "Contrôles rapides", "tray.github": "Page GitHub", "tray.openDuoVoice": "Ouvrir DuoVoice", "tray.session": "Session", "tray.favorites": "Favoris", "tray.quitSession": "Quitter la session", "tray.addParticipant": "Ajouter un participant", "tray.noFavorites": "Aucun favori enregistré",
    "language.changed": "Langue modifiée.", "autostart.enabled": "Démarrage automatique activé.", "autostart.disabled": "Démarrage automatique désactivé.", "trayIcon.enabled": "Icône du systray activée.", "trayIcon.disabled": "Icône du systray désactivée. Le démarrage minimisé est désactivé pour garder DuoVoice accessible."
  },
  es: {
    "brand.subtitle": "Intercom local", "status.offline": "Sin conexión", "status.connected": "Conectado",
    "common.settings": "Ajustes", "common.quit": "Salir", "common.cancel": "Cancelar", "common.close": "Cerrar", "common.open": "Abrir", "common.apply": "Aplicar cambios", "common.reset": "Restablecer valores",
    "update.checking": "Buscando actualizaciones…", "update.current": "No hay actualizaciones · Haz clic para comprobar", "update.available": "Actualización disponible · v{version} · Haz clic para descargar", "update.error": "No se pudo comprobar · Haz clic para reintentar", "update.preparing": "Preparando v{version}…", "update.downloading": "Descargando v{version}…", "update.installing": "Instalando v{version}…",
    "group.title": "Sesión", "group.subtitle": "Uno a uno o grupo LAN", "group.empty": "No hay ninguna sesión configurada.", "group.members": "Participantes activos", "group.add": "Añadir a la sesión", "group.remove": "Quitar de la sesión", "group.limit": "Una sesión de grupo puede contener hasta 12 participantes, incluido este equipo.", "group.reconnecting": "Reconectando…", "group.duo": "Dúo", "group.groupMode": "Grupo LAN", "group.trayTitle": "Sesión", "group.trayDuo": "Dúo · {count} PC", "group.trayGroup": "Grupo · {count} PC", "group.none": "Sin sesión", "group.duoSummary": "Dúo · {count} participantes", "group.groupSummary": "Grupo · {count} participantes", "group.participantsTitle": "Participantes de la sesión", "group.participantCount": "{count} participantes", "group.popupHint": "Usa el botón + junto al equipo seleccionado para añadirlo a esta sesión.",
    "group.duoHint": "Conexión directa", "group.groupHint": "Salas con nombre en la LAN", "group.rooms": "Salas de grupo", "group.roomsShort": "salas", "group.visibleHint": "Las salas aparecen automáticamente en otros equipos DuoVoice de la red local.", "group.roomPlaceholder": "Nombre de sala, p. ej. Gaming", "group.createRoom": "Crear", "group.availableRooms": "Salas disponibles", "group.noRooms": "Aún no hay salas visibles. Crea una o espera a otro equipo DuoVoice.", "group.join": "Entrar", "group.leave": "Salir", "group.host": "Host", "group.hostUnavailable": "Host no disponible", "group.full": "Completa", "group.roomLabel": "Sala", "group.created": "Sala {name} creada y visible en la LAN.", "group.createFailed": "No se pudo crear la sala", "group.joined": "Te uniste a la sala {name}.", "group.joinFailed": "No se pudo entrar en la sala", "group.left": "Has salido de la sala.", "group.you": "Tú", "group.waiting": "Sala activa", "group.closed": "El host cerró la sala.",
    "recent.title": "Conexiones recientes", "recent.desc": "Los últimos equipos LAN utilizados.", "recent.empty": "Aún no hay conexiones recientes.",
    "diagnostics.title": "Diagnóstico", "diagnostics.desc": "Información útil para resolver problemas de audio y LAN.", "diagnostics.computer": "Equipo", "diagnostics.ip": "IPv4 local", "diagnostics.ports": "Puertos LAN", "diagnostics.engine": "Motor de audio", "diagnostics.peers": "Equipos de sesión", "diagnostics.devices": "Dispositivos activos", "diagnostics.log": "Archivo de registro",
    "connection.title": "Conexión", "connection.subtitle": "Elige el PC con el que quieres comunicarte.", "connection.machineName": "Nombre de este equipo", "connection.machinePlaceholder": "Nombre visible en la red", "connection.remote": "Equipo remoto", "connection.searching": "Buscando un PC…", "connection.none": "No se detectó ningún PC — añade una IP", "connection.favorites": "Favoritos", "connection.quickActions": "Acciones rápidas", "connection.ipPlaceholder": "Dirección IP, ej. 192.168.1.25", "connection.ipHint": "También puedes añadir una dirección IP directamente.", "connection.connect": "Conectar", "connection.disconnect": "Desconectar", "connection.available": "Disponible", "connection.unavailable": "No disponible", "connection.favoriteAdded": "{name} añadido a favoritos.", "connection.favoriteRemoved": "Favorito eliminado.", "connection.favoritesCount": "{count} favoritos",
    "audio.title": "Audio", "audio.subtitle": "Micrófono y salida del PC.", "audio.microphone": "Micrófono", "audio.output": "Salida de audio", "audio.noise": "Reducción de ruido", "audio.disabled": "Desactivada", "audio.enabled": "Activada", "audio.noiseSettings": "Ajustes", "audio.localRnnoise": "RNNoise · procesamiento local", "audio.intensity": "Intensidad", "audio.moreSuppression": "Más alto = mayor supresión", "audio.natural": "Natural", "audio.balanced": "Equilibrado", "audio.aggressive": "Agresivo", "audio.noiseHint": "La reducción de ruido se aplica al micrófono antes del envío por red.", "audio.remoteVolume": "Volumen remoto", "audio.boost": "Permitir volumen superior al 100%", "audio.mute": "Silenciar", "audio.unmute": "Reactivar", "audio.actions": "Acciones de audio", "audio.actionsDesc": "Herramientas rápidas para la configuración de audio actual.", "audio.test": "Probar audio", "audio.testing": "Probando…", "audio.testDone": "Prueba reproducida en la salida seleccionada.", "audio.testFailed": "La prueba de audio falló", "audio.monitor": "Probar micrófono", "audio.monitoring": "Detener prueba", "audio.monitorHint": "La monitorización del micrófono está activa en la salida seleccionada.", "audio.monitorStopped": "Monitorización del micrófono detenida.", "audio.monitorFailed": "La prueba del micrófono falló",
    "state.title": "Estado", "state.searching": "Buscando equipos en la red local…", "state.latency": "Latencia de audio", "state.mode": "Modo", "state.lan": "LAN directa", "state.active": "Audio bidireccional activo.", "state.disconnected": "Desconectado.", "state.network": "Red", "state.session": "Sesión", "state.discovery": "Detección LAN", "state.ports": "Puertos",
    "settings.title": "Ajustes", "settings.subtitle": "Preferencias de DuoVoice", "settings.version": "Versión", "settings.versionDesc": "Versión instalada y actualizaciones.", "settings.installedVersion": "Versión instalada", "settings.versionHint": "Haz clic en la versión para elegir otra release.", "settings.history": "Historial", "settings.lastUpdateUnavailable": "Última actualización: no disponible", "settings.startup": "Inicio", "settings.startupDesc": "Controla el comportamiento al iniciar.", "settings.autostart": "Iniciar DuoVoice con Windows", "settings.trayIcon": "Mostrar el icono en la bandeja", "settings.startHidden": "Iniciar minimizado en la bandeja", "settings.savedAutomatically": "Los ajustes se guardan automáticamente.", "settings.close": "Cierre", "settings.closeDesc": "Elige qué hace el botón X.", "settings.closeAction": "Acción del botón cerrar", "settings.minimizeTray": "Minimizar a la bandeja", "settings.quitDuoVoice": "Salir de DuoVoice", "settings.closeHint": "En modo bandeja, DuoVoice también desaparece de la barra de tareas.", "settings.language": "Idioma", "settings.languageDesc": "Elige el idioma de la aplicación.", "settings.appearance": "Apariencia", "settings.appearanceDesc": "Elige un color de acento suave.", "settings.themesPlus": "Temas++", "settings.themesPlusDesc": "Aplica una paleta completa a DuoVoice y a la bandeja.", "settings.scale": "Escala de la interfaz", "settings.scaleDesc": "Ajusta el tamaño de DuoVoice a tu pantalla.", "settings.mainApp": "Aplicación principal", "settings.trayControl": "Controles de la bandeja", "settings.audio": "Audio", "settings.audioDesc": "Los dispositivos, volumen y reducción de ruido se conservan entre inicios.", "settings.savedVolume": "Volumen guardado", "settings.noiseReduction": "Reducción de ruido",
    "version.choose": "Elegir una versión", "version.chooseDesc": "Reinstala una versión anterior firmada de DuoVoice.", "version.searching": "Buscando versiones disponibles…", "version.installQuestion": "¿Instalar {version}?", "version.install": "Instalar", "version.none": "No hay una versión anterior firmada disponible.", "quit.title": "¿Salir de DuoVoice?", "quit.body": "La aplicación y el audio se detendrán por completo.", "tray.host": "Host", "tray.noHost": "Ningún host conectado", "tray.choosePc": "Elegir un PC…", "tray.noDetected": "Ningún host detectado", "tray.connection": "Conexión", "tray.quickControls": "Controles rápidos", "tray.github": "Página de GitHub", "tray.openDuoVoice": "Abrir DuoVoice", "tray.session": "Sesión", "tray.favorites": "Favoritos", "tray.quitSession": "Salir de la sesión", "tray.addParticipant": "Añadir participante", "tray.noFavorites": "No hay favoritos guardados", "language.changed": "Idioma cambiado.", "autostart.enabled": "Inicio automático activado.", "autostart.disabled": "Inicio automático desactivado.", "trayIcon.enabled": "Icono de la bandeja activado.", "trayIcon.disabled": "Icono de la bandeja desactivado. El inicio minimizado se desactiva para mantener DuoVoice accesible."
  },
  de: {
    "brand.subtitle": "Lokale Gegensprechanlage", "status.offline": "Offline", "status.connected": "Verbunden",
    "common.settings": "Einstellungen", "common.quit": "Beenden", "common.cancel": "Abbrechen", "common.close": "Schließen", "common.open": "Öffnen", "common.apply": "Änderungen anwenden", "common.reset": "Standard wiederherstellen",
    "update.checking": "Suche nach Updates…", "update.current": "Kein Update verfügbar · Zum Prüfen klicken", "update.available": "Update verfügbar · v{version} · Zum Herunterladen klicken", "update.error": "Prüfung nicht möglich · Zum Wiederholen klicken", "update.preparing": "v{version} wird vorbereitet…", "update.downloading": "v{version} wird heruntergeladen…", "update.installing": "v{version} wird installiert…",
    "group.title": "Sitzung", "group.subtitle": "Direkt oder LAN-Gruppe", "group.empty": "Keine Sitzung konfiguriert.", "group.members": "Aktive Teilnehmer", "group.add": "Zur Sitzung hinzufügen", "group.remove": "Aus Sitzung entfernen", "group.limit": "Eine Gruppensitzung kann bis zu 12 Teilnehmer enthalten, einschließlich dieses Computers.", "group.reconnecting": "Verbindung wird wiederhergestellt…", "group.duo": "Duo", "group.groupMode": "LAN-Gruppe", "group.trayTitle": "Sitzung", "group.trayDuo": "Duo · {count} PCs", "group.trayGroup": "Gruppe · {count} PCs", "group.none": "Keine Sitzung", "group.duoSummary": "Duo · {count} Teilnehmer", "group.groupSummary": "Gruppe · {count} Teilnehmer", "group.participantsTitle": "Sitzungsteilnehmer", "group.participantCount": "{count} Teilnehmer", "group.popupHint": "Mit der + Schaltfläche neben dem ausgewählten PC fügst du ihn dieser Sitzung hinzu.",
    "group.duoHint": "Direkte Verbindung", "group.groupHint": "Benannte Räume im LAN", "group.rooms": "Gruppenräume", "group.roomsShort": "Räume", "group.visibleHint": "Räume werden automatisch auf anderen DuoVoice-PCs im lokalen Netzwerk angezeigt.", "group.roomPlaceholder": "Raumname, z. B. Gaming", "group.createRoom": "Erstellen", "group.availableRooms": "Verfügbare Räume", "group.noRooms": "Noch kein Raum sichtbar. Erstelle einen oder warte auf einen anderen DuoVoice-PC.", "group.join": "Beitreten", "group.leave": "Verlassen", "group.host": "Host", "group.hostUnavailable": "Host nicht verfügbar", "group.full": "Voll", "group.roomLabel": "Raum", "group.created": "Raum {name} erstellt und im LAN sichtbar.", "group.createFailed": "Raum konnte nicht erstellt werden", "group.joined": "Raum {name} beigetreten.", "group.joinFailed": "Raum konnte nicht betreten werden", "group.left": "Raum verlassen.", "group.you": "Du", "group.waiting": "Raum aktiv", "group.closed": "Der Host hat den Raum geschlossen.",
    "recent.title": "Letzte Verbindungen", "recent.desc": "Die zuletzt verwendeten LAN-Teilnehmer.", "recent.empty": "Noch keine letzte Verbindung.",
    "diagnostics.title": "Diagnose", "diagnostics.desc": "Nützliche Informationen zur Audio- und LAN-Fehlersuche.", "diagnostics.computer": "Computer", "diagnostics.ip": "Lokale IPv4", "diagnostics.ports": "LAN-Ports", "diagnostics.engine": "Audio-Engine", "diagnostics.peers": "Sitzungsteilnehmer", "diagnostics.devices": "Aktive Geräte", "diagnostics.log": "Protokolldatei",
    "connection.title": "Verbindung", "connection.subtitle": "Wähle den PC für die Kommunikation.", "connection.machineName": "Name dieses Geräts", "connection.machinePlaceholder": "Im Netzwerk sichtbarer Name", "connection.remote": "Entfernter Computer", "connection.searching": "Suche nach einem PC…", "connection.none": "Kein PC erkannt — IP hinzufügen", "connection.favorites": "Favoriten", "connection.quickActions": "Schnellaktionen", "connection.ipPlaceholder": "IP-Adresse, z. B. 192.168.1.25", "connection.ipHint": "Du kannst auch direkt eine IP-Adresse hinzufügen.", "connection.connect": "Verbinden", "connection.disconnect": "Trennen", "connection.available": "Verfügbar", "connection.unavailable": "Nicht verfügbar", "connection.favoriteAdded": "{name} zu Favoriten hinzugefügt.", "connection.favoriteRemoved": "Favorit entfernt.", "connection.favoritesCount": "{count} Favoriten",
    "audio.title": "Audio", "audio.subtitle": "Mikrofon und PC-Ausgabe.", "audio.microphone": "Mikrofon", "audio.output": "Audioausgabe", "audio.noise": "Rauschunterdrückung", "audio.disabled": "Deaktiviert", "audio.enabled": "Aktiviert", "audio.noiseSettings": "Einstellungen", "audio.localRnnoise": "RNNoise · lokale Verarbeitung", "audio.intensity": "Intensität", "audio.moreSuppression": "Höher = stärkere Unterdrückung", "audio.natural": "Natürlich", "audio.balanced": "Ausgewogen", "audio.aggressive": "Aggressiv", "audio.noiseHint": "Die Rauschunterdrückung wird vor der Netzwerkübertragung auf das Mikrofon angewendet.", "audio.remoteVolume": "Remote-Lautstärke", "audio.boost": "Lautstärke über 100% erlauben", "audio.mute": "Stumm", "audio.unmute": "Ton an", "audio.actions": "Audio-Aktionen", "audio.actionsDesc": "Schnellwerkzeuge für die aktuelle Audio-Konfiguration.", "audio.test": "Audio testen", "audio.testing": "Test läuft…", "audio.testDone": "Audiotest über die ausgewählte Ausgabe abgespielt.", "audio.testFailed": "Audiotest fehlgeschlagen", "audio.monitor": "Mikrofon testen", "audio.monitoring": "Mikrofontest stoppen", "audio.monitorHint": "Das Mikrofon-Monitoring ist auf der gewählten Ausgabe aktiv.", "audio.monitorStopped": "Mikrofon-Monitoring beendet.", "audio.monitorFailed": "Mikrofontest fehlgeschlagen",
    "state.title": "Status", "state.searching": "Suche nach Computern im lokalen Netzwerk…", "state.latency": "Audio-Latenz", "state.mode": "Modus", "state.lan": "Direktes LAN", "state.active": "Bidirektionales Audio aktiv.", "state.disconnected": "Getrennt.", "state.network": "Netzwerk", "state.session": "Sitzung", "state.discovery": "LAN-Erkennung", "state.ports": "Ports",
    "settings.title": "Einstellungen", "settings.subtitle": "DuoVoice-Einstellungen", "settings.version": "Version", "settings.versionDesc": "Installierte Version und Updates.", "settings.installedVersion": "Installierte Version", "settings.versionHint": "Auf die Version klicken, um eine andere Release zu wählen.", "settings.history": "Verlauf", "settings.lastUpdateUnavailable": "Letztes Update: nicht verfügbar", "settings.startup": "Start", "settings.startupDesc": "Startverhalten steuern.", "settings.autostart": "DuoVoice mit Windows starten", "settings.trayIcon": "Symbol im Infobereich anzeigen", "settings.startHidden": "Minimiert im Infobereich starten", "settings.savedAutomatically": "Einstellungen werden automatisch gespeichert.", "settings.close": "Schließen", "settings.closeDesc": "Wähle die Aktion der X-Schaltfläche.", "settings.closeAction": "Aktion der Schließen-Schaltfläche", "settings.minimizeTray": "In den Infobereich minimieren", "settings.quitDuoVoice": "DuoVoice beenden", "settings.closeHint": "Im Infobereich-Modus verschwindet DuoVoice auch aus der Taskleiste.", "settings.language": "Sprache", "settings.languageDesc": "Wähle die Sprache der Anwendung.", "settings.appearance": "Darstellung", "settings.appearanceDesc": "Wähle eine dezente Akzentfarbe.", "settings.themesPlus": "Themes++", "settings.themesPlusDesc": "Wendet eine vollständige Palette auf DuoVoice und den Infobereich an.", "settings.scale": "Oberflächenskalierung", "settings.scaleDesc": "Passe die Größe von DuoVoice an deinen Bildschirm an.", "settings.mainApp": "Hauptanwendung", "settings.trayControl": "Infobereich-Steuerung", "settings.audio": "Audio", "settings.audioDesc": "Geräte, Lautstärke und Rauschunterdrückung bleiben gespeichert.", "settings.savedVolume": "Gespeicherte Lautstärke", "settings.noiseReduction": "Rauschunterdrückung",
    "version.choose": "Version auswählen", "version.chooseDesc": "Eine frühere signierte DuoVoice-Version neu installieren.", "version.searching": "Verfügbare Versionen werden gesucht…", "version.installQuestion": "{version} installieren?", "version.install": "Installieren", "version.none": "Keine frühere signierte Version verfügbar.", "quit.title": "DuoVoice beenden?", "quit.body": "Anwendung und Audio werden vollständig beendet.", "tray.host": "Host", "tray.noHost": "Kein Host verbunden", "tray.choosePc": "PC auswählen…", "tray.noDetected": "Kein Host erkannt", "tray.connection": "Verbindung", "tray.quickControls": "Schnellsteuerung", "tray.github": "GitHub-Seite", "tray.openDuoVoice": "DuoVoice öffnen", "tray.session": "Sitzung", "tray.favorites": "Favoriten", "tray.quitSession": "Sitzung verlassen", "tray.addParticipant": "Teilnehmer hinzufügen", "tray.noFavorites": "Keine Favoriten gespeichert", "language.changed": "Sprache geändert.", "autostart.enabled": "Automatischer Start aktiviert.", "autostart.disabled": "Automatischer Start deaktiviert.", "trayIcon.enabled": "Infobereich-Symbol aktiviert.", "trayIcon.disabled": "Infobereich-Symbol deaktiviert. Der minimierte Start wird deaktiviert, damit DuoVoice erreichbar bleibt."
  }
};

export function normalizeLanguage(value) {
  return SUPPORTED_LANGUAGES.includes(value) ? value : DEFAULT_LANGUAGE;
}

export function getLanguage() {
  return normalizeLanguage(localStorage.getItem(LANGUAGE_KEY) || DEFAULT_LANGUAGE);
}

export function setLanguage(language) {
  const normalized = normalizeLanguage(language);
  localStorage.setItem(LANGUAGE_KEY, normalized);
  return normalized;
}

export function t(key, vars = {}, language = getLanguage()) {
  const lang = normalizeLanguage(language);
  const template = dictionaries[lang]?.[key] ?? dictionaries.en[key] ?? key;
  return String(template).replace(/\{(\w+)\}/g, (_, name) => vars[name] ?? `{${name}}`);
}

export function localeForLanguage(language = getLanguage()) {
  return ({ en: "en-US", fr: "fr-FR", es: "es-ES", de: "de-DE" })[normalizeLanguage(language)] || "en-US";
}

export function applyStaticTranslations(root = document, language = getLanguage()) {
  const lang = normalizeLanguage(language);
  document.documentElement.lang = lang;
  root.querySelectorAll("[data-i18n]").forEach((element) => {
    element.textContent = t(element.dataset.i18n, {}, lang);
  });
  root.querySelectorAll("[data-i18n-placeholder]").forEach((element) => {
    element.setAttribute("placeholder", t(element.dataset.i18nPlaceholder, {}, lang));
  });
  root.querySelectorAll("[data-i18n-title]").forEach((element) => {
    element.setAttribute("title", t(element.dataset.i18nTitle, {}, lang));
  });
  root.querySelectorAll("[data-i18n-aria]").forEach((element) => {
    element.setAttribute("aria-label", t(element.dataset.i18nAria, {}, lang));
  });
}
